/// 2026 monthly budget by entity (Revenue, S&W, EBITDA). Calendar 2026 for Longbranch/EDTC/RNGA/RNH; offset for RNAL (Feb 2026 to Jan 2027); NTM Apr 2026 to Mar 2027 for Widespread facilities (TER/Lotus/GAW/GLR/CRC). Other Expenses derivable as Revenue minus S&W minus EBITDA.
table fin_budget
	lineageTag: e2f41a02-3c41-4bbb-b56e-bac7b3d348f9

	/// Budgeted revenue from 2026 plan (calendar 2026 for RN entities; NTM Apr 2026-Mar 2027 for Widespread).
	measure 'Revenue Budget' = CALCULATE(SUM('fin_budget'[amount]), 'fin_budget'[type] = "Revenue")
		formatString: $#,##0;($#,##0)
		displayFolder: 02 Budget
		lineageTag: d89bbd93-cf3c-4177-a115-47ec121547cb

	/// Budgeted Salaries and Wages.
	measure 'S&W Budget' = CALCULATE(SUM('fin_budget'[amount]), 'fin_budget'[type] = "Salaries and Wages")
		formatString: $#,##0;($#,##0)
		displayFolder: 02 Budget
		lineageTag: 05570803-1e93-4239-b726-acb6ba71bb84

	/// Budgeted EBITDA directly from the plan (not derived). For RNH this is HQ overhead (negative).
	measure 'EBITDA Budget' = CALCULATE(SUM('fin_budget'[amount]), 'fin_budget'[type] = "EBITDA")
		formatString: $#,##0;($#,##0)
		displayFolder: 02 Budget
		lineageTag: fb530161-6a33-4655-9aee-84333db3e42b

	/// Budgeted revenue YTD, matched to actuals YTD window.
	measure 'Revenue Budget YTD' = SUMX('dim_entity', VAR fy_start = 'dim_entity'[fiscal_year_start_month] VAR today_date = TODAY() VAR todayFY = YEAR(EDATE(today_date, -(fy_start - 1))) VAR todayFP = MONTH(EDATE(today_date, -(fy_start - 1))) VAR entCode = 'dim_entity'[facility_code] RETURN CALCULATE([Revenue Budget], FILTER(ALL('fin_budget'), 'fin_budget'[entity] = entCode && 'fin_budget'[fiscal_year] = todayFY && 'fin_budget'[fiscal_period] <= todayFP)))
		formatString: $#,##0;($#,##0)
		displayFolder: 06 Fiscal YTD Budget
		lineageTag: 7d26fe7e-8e4b-4394-abfb-f820de90f85e

	/// Budgeted S&W YTD.
	measure 'S&W Budget YTD' = SUMX('dim_entity', VAR fy_start = 'dim_entity'[fiscal_year_start_month] VAR today_date = TODAY() VAR todayFY = YEAR(EDATE(today_date, -(fy_start - 1))) VAR todayFP = MONTH(EDATE(today_date, -(fy_start - 1))) VAR entCode = 'dim_entity'[facility_code] RETURN CALCULATE([S&W Budget], FILTER(ALL('fin_budget'), 'fin_budget'[entity] = entCode && 'fin_budget'[fiscal_year] = todayFY && 'fin_budget'[fiscal_period] <= todayFP)))
		formatString: $#,##0;($#,##0)
		displayFolder: 06 Fiscal YTD Budget
		lineageTag: 33275811-a99f-47a0-af7c-7beddd41f19e

	/// Budgeted EBITDA YTD.
	measure 'EBITDA Budget YTD' = SUMX('dim_entity', VAR fy_start = 'dim_entity'[fiscal_year_start_month] VAR today_date = TODAY() VAR todayFY = YEAR(EDATE(today_date, -(fy_start - 1))) VAR todayFP = MONTH(EDATE(today_date, -(fy_start - 1))) VAR entCode = 'dim_entity'[facility_code] RETURN CALCULATE([EBITDA Budget], FILTER(ALL('fin_budget'), 'fin_budget'[entity] = entCode && 'fin_budget'[fiscal_year] = todayFY && 'fin_budget'[fiscal_period] <= todayFP)))
		formatString: $#,##0;($#,##0)
		displayFolder: 06 Fiscal YTD Budget
		lineageTag: ff5851de-cd72-4f35-aec6-1ea68d91da3a

	column month_ending
		dataType: dateTime
		formatString: Long Date
		lineageTag: 97fe9106-79e3-4338-bb1e-432924516164
		summarizeBy: none
		sourceColumn: month_ending

		annotation UnderlyingDateTimeDataType = Date

	column type
		dataType: string
		lineageTag: 4f22012d-2b1b-4092-990f-a3ac2a1912c3
		summarizeBy: none
		sourceColumn: type

	column entity
		dataType: string
		lineageTag: 057a8233-3477-4f7a-93d6-9171c11f2a18
		summarizeBy: none
		sourceColumn: entity

	column amount
		dataType: double
		formatString: $#,##0;($#,##0)
		lineageTag: e08c01a6-77ec-4eef-a272-0290c5189fb5
		summarizeBy: sum
		sourceColumn: amount

	/// Fiscal year for budget row. Same logic as fin_monthly: Widespread Apr 2026-Mar 2027 = FY2026; calendar entities = calendar year.
	column fiscal_year = YEAR(EDATE('fin_budget'[month_ending], -(RELATED('dim_entity'[fiscal_year_start_month]) - 1)))
		dataType: int64
		displayFolder: Fiscal Calendar
		lineageTag: c36d8f97-c17b-41e8-86cb-241883af21df
		summarizeBy: none

	/// Fiscal period for budget row.
	column fiscal_period = MONTH(EDATE('fin_budget'[month_ending], -(RELATED('dim_entity'[fiscal_year_start_month]) - 1)))
		dataType: int64
		displayFolder: Fiscal Calendar
		lineageTag: a0554022-babd-4452-92e2-a0d9a463d713
		summarizeBy: none

	partition fin_budget = m
		mode: import
		source = let Source = #table( type table [month_ending=date, type=text, entity=text, amount=number], {{#date(2026,1,31),"Revenue","CRC",299481.0},{#date(2026,2,28),"Revenue","CRC",299481.0},{#date(2026,3,31),"Revenue","CRC",299481.0},{#date(2026,4,30),"Revenue","CRC",299481.0},{#date(2026,5,31),"Revenue","CRC",299481.0},{#date(2026,6,30),"Revenue","CRC",299481.0},{#date(2026,7,31),"Revenue","CRC",299481.0},{#date(2026,8,31),"Revenue","CRC",299481.0},{#date(2026,9,30),"Revenue","CRC",299481.0},{#date(2026,10,31),"Revenue","CRC",299481.0},{#date(2026,11,30),"Revenue","CRC",299481.0},{#date(2026,12,31),"Revenue","CRC",299481.0},{#date(2027,1,31),"Revenue","CRC",299481.0},{#date(2027,2,28),"Revenue","CRC",299481.0},{#date(2027,3,31),"Revenue","CRC",299481.0},{#date(2026,1,31),"Salaries and Wages","CRC",184453.68},{#date(2026,2,28),"Salaries and Wages","CRC",131219.89},{#date(2026,3,31),"Salaries and Wages","CRC",131219.89},{#date(2026,4,30),"Salaries and Wages","CRC",136235.52},{#date(2026,5,31),"Salaries and Wages","CRC",131219.89},{#date(2026,6,30),"Salaries and Wages","CRC",131219.89},{#date(2026,7,31),"Salaries and Wages","CRC",184453.68},{#date(2026,8,31),"Salaries and Wages","CRC",131219.89},{#date(2026,9,30),"Salaries and Wages","CRC",131219.89},{#date(2026,10,31),"Salaries and Wages","CRC",136235.52},{#date(2026,11,30),"Salaries and Wages","CRC",131219.89},{#date(2026,12,31),"Salaries and Wages","CRC",131219.89},{#date(2027,1,31),"Salaries and Wages","CRC",131219.89},{#date(2027,2,28),"Salaries and Wages","CRC",131219.89},{#date(2027,3,31),"Salaries and Wages","CRC",131219.89},{#date(2026,1,31),"EBITDA","CRC",-7569.08},{#date(2026,2,28),"EBITDA","CRC",44429.08},{#date(2026,3,31),"EBITDA","CRC",44429.08},{#date(2026,4,30),"EBITDA","CRC",44429.08},{#date(2026,5,31),"EBITDA","CRC",47132.7},{#date(2026,6,30),"EBITDA","CRC",45184.7},{#date(2026,7,31),"EBITDA","CRC",-7569.08},{#date(2026,8,31),"EBITDA","CRC",45664.7},{#date(2026,9,30),"EBITDA","CRC",45664.7},{#date(2026,10,31),"EBITDA","CRC",40649.08},{#date(2026,11,30),"EBITDA","CRC",45664.7},{#date(2026,12,31),"EBITDA","CRC",45664.7},{#date(2027,1,31),"EBITDA","CRC",45664.7},{#date(2027,2,28),"EBITDA","CRC",45664.7},{#date(2027,3,31),"EBITDA","CRC",45664.7},{#date(2026,1,31),"Revenue","Lotus",917050.0},{#date(2026,2,28),"Revenue","Lotus",917050.0},{#date(2026,3,31),"Revenue","Lotus",917050.0},{#date(2026,4,30),"Revenue","Lotus",917050.0},{#date(2026,5,31),"Revenue","Lotus",943450.0},{#date(2026,6,30),"Revenue","Lotus",913750.0},{#date(2026,7,31),"Revenue","Lotus",943450.0},{#date(2026,8,31),"Revenue","Lotus",943450.0},{#date(2026,9,30),"Revenue","Lotus",913750.0},{#date(2026,10,31),"Revenue","Lotus",943450.0},{#date(2026,11,30),"Revenue","Lotus",913750.0},{#date(2026,12,31),"Revenue","Lotus",943450.0},{#date(2027,1,31),"Revenue","Lotus",943450.0},{#date(2027,2,28),"Revenue","Lotus",854350.0},{#date(2027,3,31),"Revenue","Lotus",943450.0},{#date(2026,1,31),"Salaries and Wages","Lotus",344216.2},{#date(2026,2,28),"Salaries and Wages","Lotus",232186.13},{#date(2026,3,31),"Salaries and Wages","Lotus",232186.13},{#date(2026,4,30),"Salaries and Wages","Lotus",232186.13},{#date(2026,5,31),"Salaries and Wages","Lotus",232186.13},{#date(2026,6,30),"Salaries and Wages","Lotus",232186.13},{#date(2026,7,31),"Salaries and Wages","Lotus",344216.2},{#date(2026,8,31),"Salaries and Wages","Lotus",232186.13},{#date(2026,9,30),"Salaries and Wages","Lotus",232186.13},{#date(2026,10,31),"Salaries and Wages","Lotus",232186.13},{#date(2026,11,30),"Salaries and Wages","Lotus",232186.13},{#date(2026,12,31),"Salaries and Wages","Lotus",232186.13},{#date(2027,1,31),"Salaries and Wages","Lotus",232186.13},{#date(2027,2,28),"Salaries and Wages","Lotus",232186.13},{#date(2027,3,31),"Salaries and Wages","Lotus",232186.13},{#date(2026,1,31),"EBITDA","Lotus",418680.04},{#date(2026,2,28),"EBITDA","Lotus",435988.6},{#date(2026,3,31),"EBITDA","Lotus",398648.36},{#date(2026,4,30),"EBITDA","Lotus",418680.04},{#date(2026,5,31),"EBITDA","Lotus",435988.6},{#date(2026,6,30),"EBITDA","Lotus",398648.36},{#date(2026,7,31),"EBITDA","Lotus",317843.99},{#date(2026,8,31),"EBITDA","Lotus",427894.06},{#date(2026,9,30),"EBITDA","Lotus",399835.56},{#date(2026,10,31),"EBITDA","Lotus",429644.8},{#date(2026,11,30),"EBITDA","Lotus",398465.56},{#date(2026,12,31),"EBITDA","Lotus",429924.06},{#date(2027,1,31),"EBITDA","Lotus",425222.13},{#date(2027,2,28),"EBITDA","Lotus",342882.56},{#date(2027,3,31),"EBITDA","Lotus",428813.88},{#date(2026,1,31),"Revenue","GAW",765769.35},{#date(2026,2,28),"Revenue","GAW",765769.35},{#date(2026,3,31),"Revenue","GAW",765769.35},{#date(2026,4,30),"Revenue","GAW",742631.35},{#date(2026,5,31),"Revenue","GAW",765769.35},{#date(2026,6,30),"Revenue","GAW",742631.35},{#date(2026,7,31),"Revenue","GAW",765769.35},{#date(2026,8,31),"Revenue","GAW",765769.35},{#date(2026,9,30),"Revenue","GAW",742631.35},{#date(2026,10,31),"Revenue","GAW",765769.35},{#date(2026,11,30),"Revenue","GAW",742631.35},{#date(2026,12,31),"Revenue","GAW",765769.35},{#date(2027,1,31),"Revenue","GAW",765769.35},{#date(2027,2,28),"Revenue","GAW",696355.35},{#date(2027,3,31),"Revenue","GAW",765769.35},{#date(2026,1,31),"Salaries and Wages","GAW",357232.13},{#date(2026,2,28),"Salaries and Wages","GAW",242741.76},{#date(2026,3,31),"Salaries and Wages","GAW",242741.76},{#date(2026,4,30),"Salaries and Wages","GAW",242741.76},{#date(2026,5,31),"Salaries and Wages","GAW",242741.76},{#date(2026,6,30),"Salaries and Wages","GAW",242741.76},{#date(2026,7,31),"Salaries and Wages","GAW",357232.13},{#date(2026,8,31),"Salaries and Wages","GAW",242741.76},{#date(2026,9,30),"Salaries and Wages","GAW",242741.76},{#date(2026,10,31),"Salaries and Wages","GAW",242741.76},{#date(2026,11,30),"Salaries and Wages","GAW",242741.76},{#date(2026,12,31),"Salaries and Wages","GAW",242741.76},{#date(2027,1,31),"Salaries and Wages","GAW",242741.76},{#date(2027,2,28),"Salaries and Wages","GAW",242741.76},{#date(2027,3,31),"Salaries and Wages","GAW",242741.76},{#date(2026,1,31),"EBITDA","GAW",158577.17},{#date(2026,2,28),"EBITDA","GAW",266319.57},{#date(2026,3,31),"EBITDA","GAW",277104.89},{#date(2026,4,30),"EBITDA","GAW",266319.57},{#date(2026,5,31),"EBITDA","GAW",277104.89},{#date(2026,6,30),"EBITDA","GAW",250411.76},{#date(2026,7,31),"EBITDA","GAW",158577.17},{#date(2026,8,31),"EBITDA","GAW",272933.65},{#date(2026,9,30),"EBITDA","GAW",250767.0},{#date(2026,10,31),"EBITDA","GAW",272806.55},{#date(2026,11,30),"EBITDA","GAW",247989.76},{#date(2026,12,31),"EBITDA","GAW",273181.55},{#date(2027,1,31),"EBITDA","GAW",273151.67},{#date(2027,2,28),"EBITDA","GAW",205550.3},{#date(2027,3,31),"EBITDA","GAW",273121.56},{#date(2026,1,31),"Revenue","GLR",216934.73},{#date(2026,2,28),"Revenue","GLR",216934.73},{#date(2026,3,31),"Revenue","GLR",216934.73},{#date(2026,4,30),"Revenue","GLR",216934.73},{#date(2026,5,31),"Revenue","GLR",216934.73},{#date(2026,6,30),"Revenue","GLR",216934.73},{#date(2026,7,31),"Revenue","GLR",216934.73},{#date(2026,8,31),"Revenue","GLR",216934.73},{#date(2026,9,30),"Revenue","GLR",216934.73},{#date(2026,10,31),"Revenue","GLR",216934.73},{#date(2026,11,30),"Revenue","GLR",216934.73},{#date(2026,12,31),"Revenue","GLR",216934.73},{#date(2027,1,31),"Revenue","GLR",216934.73},{#date(2027,2,28),"Revenue","GLR",216934.73},{#date(2027,3,31),"Revenue","GLR",216934.73},{#date(2026,1,31),"Salaries and Wages","GLR",149030.69},{#date(2026,2,28),"Salaries and Wages","GLR",101996.13},{#date(2026,3,31),"Salaries and Wages","GLR",101996.13},{#date(2026,4,30),"Salaries and Wages","GLR",101996.13},{#date(2026,5,31),"Salaries and Wages","GLR",101996.13},{#date(2026,6,30),"Salaries and Wages","GLR",101996.13},{#date(2026,7,31),"Salaries and Wages","GLR",149030.69},{#date(2026,8,31),"Salaries and Wages","GLR",101996.13},{#date(2026,9,30),"Salaries and Wages","GLR",101996.13},{#date(2026,10,31),"Salaries and Wages","GLR",101996.13},{#date(2026,11,30),"Salaries and Wages","GLR",101996.13},{#date(2026,12,31),"Salaries and Wages","GLR",101996.13},{#date(2027,1,31),"Salaries and Wages","GLR",101996.13},{#date(2027,2,28),"Salaries and Wages","GLR",101996.13},{#date(2027,3,31),"Salaries and Wages","GLR",101996.13},{#date(2026,1,31),"EBITDA","GLR",-37749.18},{#date(2026,2,28),"EBITDA","GLR",16160.38},{#date(2026,3,31),"EBITDA","GLR",13900.38},{#date(2026,4,30),"EBITDA","GLR",16160.38},{#date(2026,5,31),"EBITDA","GLR",13900.38},{#date(2026,6,30),"EBITDA","GLR",12380.38},{#date(2026,7,31),"EBITDA","GLR",-37749.18},{#date(2026,8,31),"EBITDA","GLR",11078.38},{#date(2026,9,30),"EBITDA","GLR",9365.01},{#date(2026,10,31),"EBITDA","GLR",10978.08},{#date(2026,11,30),"EBITDA","GLR",7165.54},{#date(2026,12,31),"EBITDA","GLR",5663.21},{#date(2027,1,31),"EBITDA","GLR",12380.38},{#date(2027,2,28),"EBITDA","GLR",12380.38},{#date(2027,3,31),"EBITDA","GLR",10479.66},{#date(2026,1,31),"Revenue","TER",574689.78},{#date(2026,2,28),"Revenue","TER",574689.78},{#date(2026,3,31),"Revenue","TER",574689.78},{#date(2026,4,30),"Revenue","TER",574689.78},{#date(2026,5,31),"Revenue","TER",592644.78},{#date(2026,6,30),"Revenue","TER",574689.78},{#date(2026,7,31),"Revenue","TER",592644.78},{#date(2026,8,31),"Revenue","TER",592644.78},{#date(2026,9,30),"Revenue","TER",574689.78},{#date(2026,10,31),"Revenue","TER",592644.78},{#date(2026,11,30),"Revenue","TER",574689.78},{#date(2026,12,31),"Revenue","TER",592644.78},{#date(2027,1,31),"Revenue","TER",592644.78},{#date(2027,2,28),"Revenue","TER",538779.78},{#date(2027,3,31),"Revenue","TER",592644.78},{#date(2026,1,31),"Salaries and Wages","TER",343397.55},{#date(2026,2,28),"Salaries and Wages","TER",237314.97},{#date(2026,3,31),"Salaries and Wages","TER",237314.97},{#date(2026,4,30),"Salaries and Wages","TER",237314.97},{#date(2026,5,31),"Salaries and Wages","TER",237314.97},{#date(2026,6,30),"Salaries and Wages","TER",237314.97},{#date(2026,7,31),"Salaries and Wages","TER",343397.55},{#date(2026,8,31),"Salaries and Wages","TER",237314.97},{#date(2026,9,30),"Salaries and Wages","TER",237314.97},{#date(2026,10,31),"Salaries and Wages","TER",237314.97},{#date(2026,11,30),"Salaries and Wages","TER",237314.97},{#date(2026,12,31),"Salaries and Wages","TER",237314.97},{#date(2027,1,31),"Salaries and Wages","TER",237314.97},{#date(2027,2,28),"Salaries and Wages","TER",237314.97},{#date(2027,3,31),"Salaries and Wages","TER",237314.97},{#date(2026,1,31),"EBITDA","TER",59098.87},{#date(2026,2,28),"EBITDA","TER",147944.66},{#date(2026,3,31),"EBITDA","TER",165181.46},{#date(2026,4,30),"EBITDA","TER",147944.66},{#date(2026,5,31),"EBITDA","TER",165181.46},{#date(2026,6,30),"EBITDA","TER",147944.66},{#date(2026,7,31),"EBITDA","TER",59098.87},{#date(2026,8,31),"EBITDA","TER",165181.46},{#date(2026,9,30),"EBITDA","TER",147944.66},{#date(2026,10,31),"EBITDA","TER",165181.46},{#date(2026,11,30),"EBITDA","TER",147944.66},{#date(2026,12,31),"EBITDA","TER",165181.46},{#date(2027,1,31),"EBITDA","TER",165181.46},{#date(2027,2,28),"EBITDA","TER",113471.06},{#date(2027,3,31),"EBITDA","TER",165181.46},{#date(2026,1,31),"Revenue","Longbranch",1293491.75},{#date(2026,2,28),"Revenue","Longbranch",1399124.75},{#date(2026,3,31),"Revenue","Longbranch",1636289.75},{#date(2026,4,30),"Revenue","Longbranch",1586965.25},{#date(2026,5,31),"Revenue","Longbranch",1818965.0},{#date(2026,6,30),"Revenue","Longbranch",1953625.25},{#date(2026,7,31),"Revenue","Longbranch",1692671.0},{#date(2026,8,31),"Revenue","Longbranch",1715223.5},{#date(2026,9,30),"Revenue","Longbranch",1630615.25},{#date(2026,10,31),"Revenue","Longbranch",1936238.0},{#date(2026,11,30),"Revenue","Longbranch",1702637.75},{#date(2026,12,31),"Revenue","Longbranch",1611482.0},{#date(2026,1,31),"Salaries and Wages","Longbranch",590240.48},{#date(2026,2,28),"Salaries and Wages","Longbranch",407892.95},{#date(2026,3,31),"Salaries and Wages","Longbranch",411776.89},{#date(2026,4,30),"Salaries and Wages","Longbranch",411776.89},{#date(2026,5,31),"Salaries and Wages","Longbranch",452123.72},{#date(2026,6,30),"Salaries and Wages","Longbranch",474037.48},{#date(2026,7,31),"Salaries and Wages","Longbranch",662800.34},{#date(2026,8,31),"Salaries and Wages","Longbranch",474037.48},{#date(2026,9,30),"Salaries and Wages","Longbranch",474037.48},{#date(2026,10,31),"Salaries and Wages","Longbranch",487703.61},{#date(2026,11,30),"Salaries and Wages","Longbranch",488795.16},{#date(2026,12,31),"Salaries and Wages","Longbranch",488795.16},{#date(2026,1,31),"EBITDA","Longbranch",490341.86},{#date(2026,2,28),"EBITDA","Longbranch",773595.62},{#date(2026,3,31),"EBITDA","Longbranch",958642.07},{#date(2026,4,30),"EBITDA","Longbranch",902482.96},{#date(2026,5,31),"EBITDA","Longbranch",1080012.04},{#date(2026,6,30),"EBITDA","Longbranch",1186846.23},{#date(2026,7,31),"EBITDA","Longbranch",745487.46},{#date(2026,8,31),"EBITDA","Longbranch",954119.94},{#date(2026,9,30),"EBITDA","Longbranch",862868.39},{#date(2026,10,31),"EBITDA","Longbranch",1139758.95},{#date(2026,11,30),"EBITDA","Longbranch",903364.14},{#date(2026,12,31),"EBITDA","Longbranch",820270.62},{#date(2026,1,31),"Revenue","EDTC",132308.0},{#date(2026,2,28),"Revenue","EDTC",149380.0},{#date(2026,3,31),"Revenue","EDTC",198462.0},{#date(2026,4,30),"Revenue","EDTC",192060.0},{#date(2026,5,31),"Revenue","EDTC",264616.0},{#date(2026,6,30),"Revenue","EDTC",256080.0},{#date(2026,7,31),"Revenue","EDTC",330770.0},{#date(2026,8,31),"Revenue","EDTC",363847.0},{#date(2026,9,30),"Revenue","EDTC",320100.0},{#date(2026,10,31),"Revenue","EDTC",297693.0},{#date(2026,11,30),"Revenue","EDTC",256080.0},{#date(2026,12,31),"Revenue","EDTC",231539.0},{#date(2026,1,31),"Salaries and Wages","EDTC",128715.27},{#date(2026,2,28),"Salaries and Wages","EDTC",95715.32},{#date(2026,3,31),"Salaries and Wages","EDTC",100605.44},{#date(2026,4,30),"Salaries and Wages","EDTC",97680.44},{#date(2026,5,31),"Salaries and Wages","EDTC",106076.93},{#date(2026,6,30),"Salaries and Wages","EDTC",108260.02},{#date(2026,7,31),"Salaries and Wages","EDTC",153360.99},{#date(2026,8,31),"Salaries and Wages","EDTC",108260.02},{#date(2026,9,30),"Salaries and Wages","EDTC",108260.02},{#date(2026,10,31),"Salaries and Wages","EDTC",108260.02},{#date(2026,11,30),"Salaries and Wages","EDTC",109351.57},{#date(2026,12,31),"Salaries and Wages","EDTC",109351.57},{#date(2026,1,31),"EBITDA","EDTC",-62367.97},{#date(2026,2,28),"EBITDA","EDTC",-12395.54},{#date(2026,3,31),"EBITDA","EDTC",29996.34},{#date(2026,4,30),"EBITDA","EDTC",18819.34},{#date(2026,5,31),"EBITDA","EDTC",82978.84},{#date(2026,6,30),"EBITDA","EDTC",72259.76},{#date(2026,7,31),"EBITDA","EDTC",101848.78},{#date(2026,8,31),"EBITDA","EDTC",180026.76},{#date(2026,9,30),"EBITDA","EDTC",136279.76},{#date(2026,10,31),"EBITDA","EDTC",113872.76},{#date(2026,11,30),"EBITDA","EDTC",71168.21},{#date(2026,12,31),"EBITDA","EDTC",46627.21},{#date(2026,1,31),"Revenue","RNGA",141360.0},{#date(2026,2,28),"Revenue","RNGA",143640.0},{#date(2026,3,31),"Revenue","RNGA",176700.0},{#date(2026,4,30),"Revenue","RNGA",250800.0},{#date(2026,5,31),"Revenue","RNGA",353400.0},{#date(2026,6,30),"Revenue","RNGA",370500.0},{#date(2026,7,31),"Revenue","RNGA",412300.0},{#date(2026,8,31),"Revenue","RNGA",441750.0},{#date(2026,9,30),"Revenue","RNGA",498750.0},{#date(2026,10,31),"Revenue","RNGA",489250.0},{#date(2026,11,30),"Revenue","RNGA",490200.0},{#date(2026,12,31),"Revenue","RNGA",420850.0},{#date(2026,1,31),"Salaries and Wages","RNGA",262378.6},{#date(2026,2,28),"Salaries and Wages","RNGA",176859.57},{#date(2026,3,31),"Salaries and Wages","RNGA",176859.57},{#date(2026,4,30),"Salaries and Wages","RNGA",182317.29},{#date(2026,5,31),"Salaries and Wages","RNGA",182317.29},{#date(2026,6,30),"Salaries and Wages","RNGA",182317.29},{#date(2026,7,31),"Salaries and Wages","RNGA",270565.19},{#date(2026,8,31),"Salaries and Wages","RNGA",182317.29},{#date(2026,9,30),"Salaries and Wages","RNGA",182317.29},{#date(2026,10,31),"Salaries and Wages","RNGA",182317.29},{#date(2026,11,30),"Salaries and Wages","RNGA",182317.29},{#date(2026,12,31),"Salaries and Wages","RNGA",182317.29},{#date(2026,1,31),"EBITDA","RNGA",-216502.25},{#date(2026,2,28),"EBITDA","RNGA",-138511.95},{#date(2026,3,31),"EBITDA","RNGA",-118556.54},{#date(2026,4,30),"EBITDA","RNGA",-63022.93},{#date(2026,5,31),"EBITDA","RNGA",36465.44},{#date(2026,6,30),"EBITDA","RNGA",50451.57},{#date(2026,7,31),"EBITDA","RNGA",888.1},{#date(2026,8,31),"EBITDA","RNGA",115469.07},{#date(2026,9,30),"EBITDA","RNGA",164516.58},{#date(2026,10,31),"EBITDA","RNGA",158108.25},{#date(2026,11,30),"EBITDA","RNGA",157097.12},{#date(2026,12,31),"EBITDA","RNGA",97140.46},{#date(2026,2,28),"Revenue","RNAL",0.0},{#date(2026,3,31),"Revenue","RNAL",0.0},{#date(2026,4,30),"Revenue","RNAL",13920.0},{#date(2026,5,31),"Revenue","RNAL",41760.0},{#date(2026,6,30),"Revenue","RNAL",69600.0},{#date(2026,7,31),"Revenue","RNAL",97440.0},{#date(2026,8,31),"Revenue","RNAL",139200.0},{#date(2026,9,30),"Revenue","RNAL",208800.0},{#date(2026,10,31),"Revenue","RNAL",250560.0},{#date(2026,11,30),"Revenue","RNAL",250560.0},{#date(2026,12,31),"Revenue","RNAL",250560.0},{#date(2027,1,31),"Revenue","RNAL",278400.0},{#date(2026,2,28),"Salaries and Wages","RNAL",9150.0},{#date(2026,3,31),"Salaries and Wages","RNAL",20079.17},{#date(2026,4,30),"Salaries and Wages","RNAL",56742.0},{#date(2026,5,31),"Salaries and Wages","RNAL",57742.0},{#date(2026,6,30),"Salaries and Wages","RNAL",58742.0},{#date(2026,7,31),"Salaries and Wages","RNAL",59742.0},{#date(2026,8,31),"Salaries and Wages","RNAL",69700.67},{#date(2026,9,30),"Salaries and Wages","RNAL",95238.33},{#date(2026,10,31),"Salaries and Wages","RNAL",96738.33},{#date(2026,11,30),"Salaries and Wages","RNAL",96738.33},{#date(2026,12,31),"Salaries and Wages","RNAL",96738.33},{#date(2027,1,31),"Salaries and Wages","RNAL",101967.67},{#date(2026,2,28),"EBITDA","RNAL",-33366.67},{#date(2026,3,31),"EBITDA","RNAL",-44295.83},{#date(2026,4,30),"EBITDA","RNAL",-74435.47},{#date(2026,5,31),"EBITDA","RNAL",-48979.07},{#date(2026,6,30),"EBITDA","RNAL",-25842.67},{#date(2026,7,31),"EBITDA","RNAL",-3506.27},{#date(2026,8,31),"EBITDA","RNAL",21514.67},{#date(2026,9,30),"EBITDA","RNAL",57393.0},{#date(2026,10,31),"EBITDA","RNAL",92922.6},{#date(2026,11,30),"EBITDA","RNAL",97962.6},{#date(2026,12,31),"EBITDA","RNAL",96922.6},{#date(2027,1,31),"EBITDA","RNAL",116679.67},{#date(2026,1,31),"Salaries and Wages","RNH",67138.89},{#date(2026,2,28),"Salaries and Wages","RNH",56525.08},{#date(2026,3,31),"Salaries and Wages","RNH",44307.69},{#date(2026,4,30),"Salaries and Wages","RNH",44307.69},{#date(2026,5,31),"Salaries and Wages","RNH",44307.69},{#date(2026,6,30),"Salaries and Wages","RNH",49476.92},{#date(2026,7,31),"Salaries and Wages","RNH",71015.38},{#date(2026,8,31),"Salaries and Wages","RNH",49476.92},{#date(2026,9,30),"Salaries and Wages","RNH",49476.92},{#date(2026,10,31),"Salaries and Wages","RNH",49476.92},{#date(2026,11,30),"Salaries and Wages","RNH",49476.92},{#date(2026,12,31),"Salaries and Wages","RNH",49476.92},{#date(2026,1,31),"EBITDA","RNH",-162456.56},{#date(2026,2,28),"EBITDA","RNH",-131248.75},{#date(2026,3,31),"EBITDA","RNH",-214031.36},{#date(2026,4,30),"EBITDA","RNH",-149031.36},{#date(2026,5,31),"EBITDA","RNH",-316036.76},{#date(2026,6,30),"EBITDA","RNH",-154200.59},{#date(2026,7,31),"EBITDA","RNH",-175739.05},{#date(2026,8,31),"EBITDA","RNH",-154200.59},{#date(2026,9,30),"EBITDA","RNH",-154200.59},{#date(2026,10,31),"EBITDA","RNH",-154200.59},{#date(2026,11,30),"EBITDA","RNH",-163133.21},{#date(2026,12,31),"EBITDA","RNH",-154200.59}} ) in Source

